FROM golang:1.22-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o /master ./cmd/master/

FROM alpine:3.19
RUN apk add --no-cache ca-certificates
COPY --from=builder /master /usr/local/bin/master
EXPOSE 8080
CMD ["master"]
